// Filter by terms and non-ASCII characters
const foreignChar = /([^\x00-\x7F]+)/gim;
const cleanMatch = /(?<!so)((^clean)|(clean$)|\W+clean\W+)(?!\W*bandit)/gim;

const filterArray = [
  "cover",
  "piano",
  "live",
  "demo",
  "slowed",
  "s l o w e d",
  "reverb",
  "r e v e r b",
  "pitch",
  "instrumental",
  "choreography",
  "performance",
  "mirrored",
  "unplugged",
  "behind the music",
  "sing along",
  "dance video",
  "tik tok",
  "tiktok",
  "karaoke",
  "shorts",
  "loop",
  "hour",
  "perform",
  "cmt",
  "acoustic",
  "amazingmusic",
  "behind the scenes",
  "audition",
  "reaction",
  "explain",
  "explanation",
  "react",
  "freestyle",
  "mtv",
  "vma",
  "chipmunk",
  "metal version",
  "male version",
  "acapella",
  "nightcore",
  "nightcrore",
  "minecraft",
  "kidz bop",
  "kidzbop",
  "verified",
  "parody",
  "pronunciation",
  "meaning",
  "music box",
  "the voice",
  "extended",
  "learn english",
  "translation",
  "traducao",
  "mashup",
  "mash-up",
  cleanMatch,
  foreignChar,
];

const mustContainArray = [
  "video",
  "audio",
  "lyrics",
  "letra",
  "official",
  "mv",
  "music video",
  "music",
];

module.exports = { filterArray, mustContainArray };
